# Generated by Django 4.2 on 2023-05-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0002_contact_portifolio_detail_project_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
    ]
