# Generated by Django 4.2 on 2023-05-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0005_portifolio_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portifolio_detail',
            old_name='project_Info',
            new_name='project_description',
        ),
    ]
