# Generated by Django 4.2 on 2023-05-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0006_rename_project_info_portifolio_detail_project_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
