# Generated by Django 4.2.3 on 2023-07-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
