# Generated by Django 4.2.3 on 2023-08-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
